### ISSUE TITLE
Check the Journals are in Flourish DB

### ISSUE THREAD

**Issue by norlab** [FlourishOA/FlourishOA#14]
http://www.mdpi.com/about/journals

**Comment by norlab** [comment]
Also https://www.openlibhums.org/journals/

**Comment by pzli3** [comment]
For openlibhums, these are the only 4 that don't exist:
https://jpl.letras.ulisboa.pt/ (2397-5563)
https://www.journal-labphon.org/ (1868-6354)
https://marvell.openlibhums.org/ (2399-7435)
https://pynchonnotes.openlibhums.org/ (0278-1891)
Don't know what category to use though...

**Comment by norlab** [comment]
Our categories are currently a mess - so your best guess is good enough

**Comment by norlab** [comment]
Added to FlourishOA db
